data_dict = {
    "symptom_index": {'Abdominal cramp': 0,
                      'Abdominal distention': 1,
                      'Abnormal behavior': 2,
                      'Abnormal bleeding': 3,
                      'Abnormal sensation': 4,
                      'Abnormally frequent': 5,
                      'Abscess': 6,
                      'Aching': 7,
                      'Acne': 8,
                      'Acquiring drinking alcohol taking lot time': 9,
                      'Affected part turning white': 10,
                      'Anemia': 11,
                      'Anxiety': 12,
                      'Arm': 13,
                      'Attack pain': 14,
                      'Back': 15,
                      'Bacterial infection': 16,
                      'Bad breath': 17,
                      'Bad smelling thin vaginal discharge': 18,
                      'Bad smelling vaginal discharge': 19,
                      'Barky cough': 20,
                      'Belching': 21,
                      'Better sitting worse lying': 22,
                      'Birth baby younger week gestational age': 23,
                      'Bleeding gum': 24,
                      'Bleeding skin': 25,
                      'Blindness': 26,
                      'Blindness one eye': 27,
                      'Blister sunlight': 28,
                      'Bloating': 29,
                      'Blood stool': 30,
                      'Blood urine': 31,
                      'Bloody diarrhea': 32,
                      'Blue': 33,
                      'Bluish skin coloration': 34,
                      'Blurred vision': 35,
                      'Blurry vision': 36,
                      'Body tremor': 37,
                      'Bone pain': 38,
                      'Bowed leg': 39,
                      'Breakdown skeletal muscle': 40,
                      'Breathing problem': 41,
                      'Bruising': 42,
                      'Burning': 43,
                      'Burning redness eye': 44,
                      'Burning stabbing pain': 45,
                      'Burning urination': 46,
                      'Certain thought repeatedly': 47,
                      'Change bowel movement': 48,
                      'Change breast shape': 49,
                      'Change color': 50,
                      'Change hair': 51,
                      'Change reflex': 52,
                      'Change skin color red black': 53,
                      'Change sleeping eating pattern': 54,
                      'Change taste': 55,
                      'Change voice': 56,
                      'Characteristic facial feature': 57,
                      'Characteristic rash': 58,
                      'Chest discomfort': 59,
                      'Chest pain': 60,
                      'Chest tightness': 61,
                      'Chill': 62,
                      'Chronic cough': 63,
                      'Chronic pain bladder': 64,
                      'Clenched fist overlapping finger': 65,
                      'Close object appear blurry': 66,
                      'Clumsy': 67,
                      'Cm lump skin': 68,
                      'Cold sweat': 69,
                      'Coma': 70,
                      'Confused thinking': 71,
                      'Confusion': 72,
                      'Constipation': 73,
                      'Coolness': 74,
                      'Coordination': 75,
                      'Cough bloody mucus': 76,
                      'Cough sputum production': 77,
                      'Coughing': 78,
                      'Coughing blood': 79,
                      'Coughing including coughing blood': 80,
                      'Coughing mucus': 81,
                      'Crawl': 82,
                      'Cry episode': 83,
                      'Dark urine': 84,
                      'Darker': 85,
                      'Daytime sleepiness': 86,
                      'Death child le one year age': 87,
                      'Decreased ability feel pain': 88,
                      'Decreased ability see': 89,
                      'Decreased ability think': 90,
                      'Decreased ability think remember': 91,
                      'Decreased ability turn': 92,
                      'Decreased appetite': 93,
                      'Decreased motivation': 94,
                      'Decreased range motion': 95,
                      'Decreased taste': 96,
                      'Decreased vision': 97,
                      'Dehydration': 98,
                      'Delayed physical growth': 99,
                      'Delirium': 100,
                      'Delusion': 101,
                      'Dementia': 102,
                      'Depending subtype abdominal pain': 103,
                      'Depends organ involved': 104,
                      'Depressed mood': 105,
                      'Depression': 106,
                      'Dermatitis herpetiformis': 107,
                      'Developmental disability': 108,
                      'Diarrhea': 109,
                      'Diarrhea may bloody': 110,
                      'Diarrhea mixed blood': 111,
                      'Diarrhoea': 112,
                      'Difficulty breathing': 113,
                      'Difficulty cutting': 114,
                      'Difficulty eating': 115,
                      'Difficulty getting pregnant': 116,
                      'Difficulty remembering recent event': 117,
                      'Difficulty swallowing': 118,
                      'Difficulty walking': 119,
                      'Dimpling skin': 120,
                      'Discharge penis': 121,
                      'Disorientation': 122,
                      'Distant object appear blurry': 123,
                      'Distorted blurred vision distance': 124,
                      'Dizziness': 125,
                      'Double vision': 126,
                      'Drinking large amount alcohol long period': 127,
                      'Drooping eyelid': 128,
                      'Dry cough': 129,
                      'Dry damp skin': 130,
                      'Dry eye': 131,
                      'Dry mouth': 132,
                      'Ear pain': 133,
                      'Easy prolonged bleeding': 134,
                      'Emotional problem': 135,
                      'Enlarged lymph node neck': 136,
                      'Enlarged spleen': 137,
                      'Enlarged thyroid': 138,
                      'Enlargement thyroid': 139,
                      'Enlargement tonsil': 140,
                      'Episode severe': 141,
                      'Erythema marginatum': 142,
                      'Excess hair': 143,
                      'Excessive amount uterine bleeding': 144,
                      'Excessive daytime sleepiness': 145,
                      'Excessive salivation': 146,
                      'Expanding area redness site tick bite': 147,
                      'Extreme sadness': 148,
                      'Extremity weakness': 149,
                      'Eye pain': 150,
                      'Eye strain': 151,
                      'Eyestrain': 152,
                      'Fast heart rate': 153,
                      'Fast heartbeat': 154,
                      'Fatigue': 155,
                      'Fear water': 156,
                      'Feel need check thing repeatedly': 157,
                      'Feeling cold': 158,
                      'Feeling faint upon standing': 159,
                      'Feeling generally unwell': 160,
                      'Feeling like passing': 161,
                      'Feeling need urinate right away': 162,
                      'Feeling tired': 163,
                      'Feeling tired time': 164,
                      'Fever': 165,
                      'Firm': 166,
                      'Flat discolored spot bump may blister': 167,
                      'Flu like illness': 168,
                      'Flu like symptom': 169,
                      'Fluid filled blister scab': 170,
                      'Fluid nipple': 171,
                      'Frequent infection': 172,
                      'Frequent urination': 173,
                      'Fullness': 174,
                      'Gas': 175,
                      'Gradual loss coordination': 176,
                      'Growth delay': 177,
                      'Gum disease': 178,
                      'Hair loss': 179,
                      'Half ring finger': 180,
                      'Hallucination': 181,
                      'Hallucination usually hearing voice': 182,
                      'Hard swelling skin': 183,
                      'Hard time reading small print': 184,
                      'Headache': 185,
                      'Hearing loss': 186,
                      'Hearing sound external sound present': 187,
                      'Heartburn': 188,
                      'Heat intolerance': 189,
                      'Heavy period': 190,
                      'High blood pressure': 191,
                      'High body temperature': 192,
                      'Hoarse voice': 193,
                      'Hold reading material farther away': 194,
                      'Impaired communication': 195,
                      'Inability child': 196,
                      'Inability move facial muscle one side': 197,
                      'Inability move feel one side body': 198,
                      'Increased breath rate': 199,
                      'Increased breathing rate': 200,
                      'Increased fat': 201,
                      'Increased heart rate': 202,
                      'Increased hunger': 203,
                      'Increased risk broken bone': 204,
                      'Increased risk infection': 205,
                      'Increased thirst': 206,
                      'Increasing weakening': 207,
                      'Index': 208,
                      'Infertility': 209,
                      'Inflamed eye': 210,
                      'Insomnia': 211,
                      'Intellectual disability': 212,
                      'Involuntary muscle movement': 213,
                      'Involuntary sleep episode': 214,
                      'Irregular edge': 215,
                      'Irregular menstrual period': 216,
                      'Irregular menstruation': 217,
                      'Irritability': 218,
                      'Irritation': 219,
                      'Itchiness': 220,
                      'Itching': 221,
                      'Itching genital area': 222,
                      'Itching result trouble sleeping': 223,
                      'Itchy': 224,
                      'Itchy blister': 225,
                      'Itchy bump': 226,
                      'Itchy ear': 227,
                      'Jaundice': 228,
                      'Jaw': 229,
                      'Jerky body movement': 230,
                      'Joint bone pain': 231,
                      'Joint swelling': 232,
                      'Large amount watery diarrhea': 233,
                      'Large forehead': 234,
                      'Large lymph node': 235,
                      'Large lymph node around neck': 236,
                      'Leg swelling': 237,
                      'Light sensitivity': 238,
                      'Little pain': 239,
                      'Localized breast pain redness': 240,
                      'Long term fatigue': 241,
                      'Loose frequent bowel movement': 242,
                      'Loose teeth': 243,
                      'Loss appetite': 244,
                      'Loss consciousness may sweating': 245,
                      'Loss hair part head body': 246,
                      'Loss lot blood childbirth': 247,
                      'Loss smell': 248,
                      'Loss vision one side': 249,
                      'Low blood pressure': 250,
                      'Low energy': 251,
                      'Low red blood cell': 252,
                      'Lower abdominal pain': 253,
                      'Lump breast': 254,
                      'Lump bump neck': 255,
                      'Maculopapular rash': 256,
                      'Malabsorption': 257,
                      'May symptom': 258,
                      'Memory problem': 259,
                      'Mental ability': 260,
                      'Mental change': 261,
                      'Mid dilated pupil': 262,
                      'Middle finger': 263,
                      'Mild moderate intellectual disability': 264,
                      'Minimal': 265,
                      'Missed period': 266,
                      'Mole increasing size': 267,
                      'Mood change': 268,
                      'Mood swing': 269,
                      'Mouth sore': 270,
                      'Mouth ulcer': 271,
                      'Multiple painful joint': 272,
                      'Muscle ache difficulty breathing': 273,
                      'Muscle cramp': 274,
                      'Muscle joint pain': 275,
                      'Muscle spasm': 276,
                      'Muscle weakness': 277,
                      'Muscle weakness beginning foot hand': 278,
                      'Muscle weakness resulting inability move': 279,
                      'Muscular pain': 280,
                      'Myalgia': 281,
                      'Nausea': 282,
                      'Nausea vomiting': 283,
                      'Nausea vomiting weight loss dehydration occur': 284,
                      'Nearly undetectable spell': 285,
                      'Nearsightedness': 286,
                      'Neck': 287,
                      'Neck stiffness': 288,
                      'Needing urinate often': 289,
                      'Newly inverted nipple': 290,
                      'Non itchy skin ulcer': 291,
                      'Non painful cyst middle eyelid': 292,
                      'Nonaligned eye': 293,
                      'None non specific': 294,
                      'Numbness': 295,
                      'Object different size eye': 296,
                      'One eye myopia eye hyperopia': 297,
                      'Opening upper lip may extend nose palate': 298,
                      'Others': 299,
                      'Overlying redness': 300,
                      'Pain along inside edge shinbone': 301,
                      'Pain area': 302,
                      'Pain around ear': 303,
                      'Pain doesnt go shingle': 304,
                      'Pain going leg lower back': 305,
                      'Pain sex': 306,
                      'Pain specific bone': 307,
                      'Painful': 308,
                      'Painful blister lower leg': 309,
                      'Painful heavy period': 310,
                      'Painful joint base big toe': 311,
                      'Painful rash occurring stripe': 312,
                      'Painful skin': 313,
                      'Painful swelling parotid gland': 314,
                      'Painful swollen joint': 315,
                      'Painful tender outer part elbow': 316,
                      'Painless': 317,
                      'Painless lump': 318,
                      'Pale color': 319,
                      'Pale skin': 320,
                      'Pallor': 321,
                      'Paralysis': 322,
                      'Patch thick': 323,
                      'Patch white skin': 324,
                      'Perform certain routine repeatedly': 325,
                      'Period vigorous shaking': 326,
                      'Persistent rough white red patch mouth lasting longer week': 327,
                      'Photophobia': 328,
                      'Physical disability': 329,
                      'Pimple like rash': 330,
                      'Pinkish': 331,
                      'Playing video game extremely long period time': 332,
                      'Poor ability tolerate cold': 333,
                      'Poor appetite': 334,
                      'Poor coordination': 335,
                      'Poor tolerance heat': 336,
                      'Post nasal drip': 337,
                      'Problem language': 338,
                      'Problem mood': 339,
                      'Problem understanding speaking': 340,
                      'Problem vision': 341,
                      'Profuse sweating': 342,
                      'Progressive muscle weakness': 343,
                      'Prolonged': 344,
                      'Prolonged cough': 345,
                      'Prominent': 346,
                      'Protein urine': 347,
                      'Psychosis': 348,
                      'Pulsing pain': 349,
                      'Purple colored skin affected area': 350,
                      'Purple colored skin lesion': 351,
                      'Raised': 352,
                      'Raised red blue lesion': 353,
                      'Random outburst laughter': 354,
                      'Rapid breathing': 355,
                      'Recurring episode wheezing': 356,
                      'Red': 357,
                      'Red eye': 358,
                      'Red purple darker skin': 359,
                      'Red rash': 360,
                      'Red scaly patch skin breast': 361,
                      'Red skin': 362,
                      'Red spot white eye': 363,
                      'Red without blister': 364,
                      'Reddish eye': 365,
                      'Redness': 366,
                      'Redness eye': 367,
                      'Repetitive behavior': 368,
                      'Restricted interest': 369,
                      'Right lower abdominal pain': 370,
                      'Rigidity': 371,
                      'Ringing ear heartbeat': 372,
                      'Rough skin growth': 373,
                      'Runny nose': 374,
                      'Scaly patch skin': 375,
                      'Scratchiness': 376,
                      'Seizure': 377,
                      'Sensitivity smell': 378,
                      'Sensitivity sound': 379,
                      'Severe intellectual disability': 380,
                      'Severe pain': 381,
                      'Severe pain lower back abdomen': 382,
                      'Shakiness': 383,
                      'Shaking': 384,
                      'Sharp chest pain': 385,
                      'Shivering': 386,
                      'Shock like pain one side face last second minute': 387,
                      'Short height': 388,
                      'Short stature': 389,
                      'Shortness breath': 390,
                      'Sit': 391,
                      'Skin blister': 392,
                      'Skin breakdown': 393,
                      'Skin lesion generally pink color project outward': 394,
                      'Skin peeling': 395,
                      'Sleep problem': 396,
                      'Sleeping problem': 397,
                      'Slowness movement': 398,
                      'Small': 399,
                      'Small blister break open form painful ulcer': 400,
                      'Small blister surrounding swelling': 401,
                      'Small face': 402,
                      'Small head': 403,
                      'Small jaw': 404,
                      'Sneezing': 405,
                      'Social withdrawal': 406,
                      'Sometimes symptom': 407,
                      'Sore arm leg': 408,
                      'Sore throat': 409,
                      'Sore wrist': 410,
                      'Stiff muscle': 411,
                      'Stiff neck': 412,
                      'Stiffness': 413,
                      'Stomach pain': 414,
                      'Stroke': 415,
                      'Stuffy itchy nose': 416,
                      'Stunted growth': 417,
                      'Sudden': 418,
                      'Sudden loss muscle strength': 419,
                      'Sweat': 420,
                      'Swell pain near tumor': 421,
                      'Swelling': 422,
                      'Swelling abdomen': 423,
                      'Swelling around eye': 424,
                      'Swelling hand foot': 425,
                      'Swollen': 426,
                      'Swollen hand foot': 427,
                      'Swollen lymph node': 428,
                      'Taste acid': 429,
                      'Temporary fleeting vision one eye': 430,
                      'Tender breast': 431,
                      'Testicular pain': 432,
                      'Tingling': 433,
                      'Tingling hand foot': 434,
                      'Tingling thumb': 435,
                      'Tiredness': 436,
                      'Tooth loss': 437,
                      'Tremor': 438,
                      'Triangular tissue growth cornea': 439,
                      'Trouble breathing nose': 440,
                      'Trouble coordination': 441,
                      'Trouble opening mouth': 442,
                      'Trouble seeing': 443,
                      'Trouble sensation': 444,
                      'Trouble sleeping': 445,
                      'Trouble social interaction': 446,
                      'Trouble speaking': 447,
                      'Trouble swallowing': 448,
                      'Trouble talking': 449,
                      'Trouble walking': 450,
                      'Typically none': 451,
                      'Ulcer': 452,
                      'Ulcer around genitals': 453,
                      'Ulceration': 454,
                      'Unable move': 455,
                      'Unexplained weight loss': 456,
                      'Unintended weight loss': 457,
                      'Unpleasant smell present breath': 458,
                      'Upper abdominal pain': 459,
                      'Usage resulting problem': 460,
                      'Vaginal bleeding': 461,
                      'Vaginal bleeding without pain': 462,
                      'Vaginal discharge': 463,
                      'Variable': 464,
                      'Vary depending part brain involved': 465,
                      'Varying degree muscle weakness': 466,
                      'Velvety skin': 467,
                      'Vision loss': 468,
                      'Vomiting': 469,
                      'Warm': 470,
                      'Wart': 471,
                      'Watery eye': 472,
                      'Weak grip': 473,
                      'Weak muscle': 474,
                      'Weakness limb': 475,
                      'Weakness numbness affected leg': 476,
                      'Webbed neck': 477,
                      'Weight gain': 478,
                      'Wet': 479,
                      'Wheezing': 480,
                      'White patch vaginal discharge': 481,
                      'Widespread pain': 482,
                      'Withdrawal occurring stopping': 483,
                      'Worrying': 484,
                      'Yellow skin': 485,
                      'Yellowish coloration skin white eye': 486,
                      'Yellowish skin': 487,
                      'Yellowish skin crust': 488},
    "predictions_classes": ['Abscess', 'Acquired Capillary Haemangioma of Eyelid',
                            'Acquired Immuno Deficiency Syndrome',
                            'Acute encephalitis syndrome', 'Adult Inclusion Conjunctivitis',
                            'Alcohol Abuse and Alcoholism', 'Alopecia (hair loss)',
                            'Alzheimer', 'Amaurosis Fugax', 'Amblyopia', 'Amoebiasis',
                            'Anaemia', 'Aniseikonia', 'Anisometropia',
                            'Antepartum hemorrhage (Bleeding in late pregnancy)', 'Anthrax',
                            'Anxiety', 'Appendicitis', 'Arthritis',
                            'Asbestos-related diseases', 'Aseptic meningitis', 'Asthma',
                            'Astigmatism', 'Atrophy', 'Autism', 'Bad Breath (Halitosis)',
                            "Bell's Palsy", 'Beriberi', 'Black Death', 'Bleeding Gums',
                            'Blindness', 'Botulism', 'Brain Tumour',
                            'Breast Cancer / Carcinoma', 'Bronchitis', 'Brucellosis',
                            'Bubonic plague', 'Bunion', 'Burns', 'Calculi',
                            'Campylobacter infection', 'Cancer', 'Candidiasis',
                            'Carbon monoxide poisoning', 'Carpal Tunnel Syndrome', 'Cavities',
                            'Celiacs disease', 'Cerebral palsy', 'Chagas disease', 'Chalazion',
                            'Chickenpox', 'Chikungunya Fever', 'Childhood Exotropia',
                            'Chlamydia', 'Cholera', 'Chorea', 'Chronic fatigue syndrome',
                            'Chronic obstructive pulmonary disease (COPD)',
                            'Cleft Lip and Cleft Palate', 'Colitis', 'Colorectal Cancer',
                            'Common cold', 'Condyloma', 'Congenital anomalies (birth defects)',
                            'Congestive heart disease', 'Corneal Abrasion',
                            'Coronary Heart Disease', 'Coronavirus disease 2019 (COVID-19)',
                            'Cough', 'Crimean Congo haemorrhagic fever (CCHF)', 'Dehydration',
                            'Dementia', 'Dengue', 'Diabetes Mellitus', 'Diabetic Retinopathy',
                            'Diarrhea', 'Diphtheria', "Down's Syndrome",
                            'Dracunculiasis (guinea-worm disease)', 'Dysentery',
                            'Ear infection', 'Early pregnancy loss', 'Ebola', 'Eclampsia',
                            'Ectopic pregnancy', 'Eczema', 'Endometriosis', 'Epilepsy',
                            'Fibroids', 'Fibromyalgia', 'Food Poisoning', 'Frost Bite', 'GERD',
                            'Gaming disorder', 'Gangrene', 'Gastroenteritis', 'Genital herpes',
                            'Glaucoma', 'Goitre', 'Gonorrhea', 'Guillain-Barré syndrome',
                            'Haemophilia', 'Hand, Foot and Mouth Disease',
                            'Heat-Related Illnesses and Heat waves', 'Hepatitis',
                            'Hepatitis A', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D',
                            'Hepatitis E', 'Herpes Simplex', 'High risk pregnancy',
                            'Human papillomavirus', 'Hypermetropia', 'Hyperthyroidism',
                            'Hypothyroid', 'Hypotonia', 'Impetigo',
                            'Inflammatory Bowel Disease', 'Influenza', 'Insomnia',
                            'Interstitial cystitis', 'Iritis', 'Iron Deficiency Anemia',
                            'Irritable bowel syndrome', 'Japanese Encephalitis', 'Jaundice',
                            'Kala-azar/ Leishmaniasis', 'Kaposi’s Sarcoma',
                            'Keratoconjunctivitis Sicca (Dry eye syndrome)', 'Keratoconus',
                            'Kuru', 'Laryngitis', 'Lead poisoning', 'Legionellosis', 'Leprosy',
                            'Leptospirosis', 'Leukemia', 'Lice', 'Lung cancer',
                            'Lupus erythematosus', 'Lyme disease', 'Lymphoma',
                            'Mad cow disease', 'Malaria', 'Marburg fever', 'Mastitis',
                            'Measles', 'Melanoma',
                            'Middle East respiratory syndrome coronavirus (MERS‐CoV)',
                            'Migraine', 'Mononucleosis', 'Mouth Breathing', 'Multiple myeloma',
                            'Multiple sclerosis', 'Mumps', 'Muscular dystrophy',
                            'Myasthenia gravis', 'Myelitis',
                            'Myocardial Infarction (Heart Attack)', 'Myopia', 'Narcolepsy',
                            'Nasal Polyps',
                            'Nausea and Vomiting of Pregnancy and  Hyperemesis gravidarum',
                            'Necrotizing Fasciitis',
                            'Neonatal Respiratory Disease Syndrome(NRDS)', 'Neoplasm',
                            'Neuralgia', 'Nipah virus infection', 'Obesity',
                            'Obsessive Compulsive Disorder', 'Oral Cancer', 'Orbital Dermoid',
                            'Osteoarthritis', 'Osteomyelitis', 'Osteoporosis',
                            'Paratyphoid fever', "Parkinson's Disease",
                            'Pelvic inflammatory disease', 'Perennial Allergic Conjunctivitis',
                            'Pericarditis', 'Peritonitis', 'Pinguecula', 'Pneumonia',
                            'Poliomyelitis', 'Polycystic ovary syndrome (PCOS)', 'Porphyria',
                            'Post Menopausal Bleeding', 'Post-herpetic neuralgia',
                            'Postpartum depression/ Perinatal depression', 'Preeclampsia',
                            'Premenstrual syndrome', 'Presbyopia', 'Preterm birth', 'Progeria',
                            'Psoriasis', 'Puerperal sepsis', 'Pulmonary embolism',
                            'Ques fever', 'Quinsy', 'Rabies', "Raynaud's Phenomenon",
                            'Repetitive strain injury', 'Rheumatic fever', 'Rheumatism',
                            'Rickets', 'Rift Valley fever', 'Rocky Mountain spotted fever',
                            'Rubella', 'SARS', 'SIDS', 'Sarcoidosis', 'Sarcoma', 'Scabies',
                            'Scarlet fever', 'Schizophrenia', 'Sciatica', 'Scrapie',
                            'Scrub Typhus', 'Scurvy', 'Sepsis',
                            'Sexually transmitted infections (STIs)', 'Shaken Baby Syndrome',
                            'Shigellosis', 'Shin splints', 'Shingles', 'Sickle-cell anemia',
                            'Smallpox', 'Stevens-Johnson syndrome', 'Stomach ulcers',
                            'Strep throat', 'Stroke', 'Sub-conjunctival Haemorrhage',
                            'Syphilis', 'Taeniasis', 'Taeniasis/cysticercosis',
                            'Tay-Sachs disease', 'Tennis elbow', 'Tetanus', 'Thalassaemia',
                            'Tinnitus', 'Tonsillitis', 'Toxic shock syndrome', 'Trachoma',
                            'Trichinosis', 'Trichomoniasis', 'Tuberculosis', 'Tularemia',
                            'Turners Syndrome', 'Urticaria', 'Varicose Veins',
                            'Vasovagal syncope', 'Vitamin B12 Deficiency', 'Vitiligo',
                            'Warkany syndrome', 'Warts', 'Yaws', 'Yellow Fever',
                            'Zika virus disease', 'lactose intolerance', 'papilloedema']
}
